book/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    PageSitemap, ArticleSitemap
)
from .views import (
    BookListView, BookDetailView,
    PageDetailView, PageCreateView, PageUpdateView,
    ArticleListView, ArticleDetailView, ArticleCategoryListView, ArticleCreateView, ArticleUpdateView,
)

app_name = 'book'

sitemaps_page = {
    'sitemap': PageSitemap(),
}

sitemaps_article = {
    'sitemap': ArticleSitemap(),
}

urlpatterns = [
    url(r'^$',
        BookListView.as_view(), name='book-list'),
    url(r'^(?P<slug>[-\w]+)/$',
        BookDetailView.as_view(), name='book-detail'),

    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/$',
        PageDetailView.as_view(), name='page-detail'),
    url(r'^(?P<book>[-\w]+)/create$',
        PageCreateView.as_view(), name='page-create'),
    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/update/',
        PageUpdateView.as_view(), name='page-update'),

    url(r'^article/(?P<category>[-\w]+)/$',
        ArticleListView.as_view(), name='article-list'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/$',
        ArticleDetailView.as_view(), name='article-detail'),
    url(r'^article/(?P<category>[-\w]+)/create$',
        ArticleCreateView.as_view(), name='article-create'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/update/',
        ArticleUpdateView.as_view(), name='article-update'),
    url(r'^article/(?P<category>[-\w]+)/category/(?P<slug>[-\w]+)$',
        ArticleCategoryListView.as_view(), name='article-category-list'),

    url(r'^sitemap-page\.xml$',
        sitemap, {'sitemaps': sitemaps_page}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-article\.xml$',
        sitemap, {'sitemaps': sitemaps_article}, name='django.contrib.sitemaps.views.sitemap'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin

from rakmai.views import HomeView

urlpatterns = [
    url(r'^$',
        HomeView.as_view(), name='home'),
    url(r'{}'.format(settings.ADMIN_URL),
        admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^voca/', include('voca.urls', namespace='voca')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^help/', include('help.urls', namespace='help')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.GOOGLE_OTP_ENABLED:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite

help/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    NoticeSitemap, PostSitemap
)
from .views import (
    PostDetailView, NoticeDetailView, NoticeListView,
    ContactCreateView, ContactDoneView,
)

app_name = 'help'

sitemaps_notice = {
    'sitemap': NoticeSitemap(),
}

sitemaps_post = {
    'sitemap': PostSitemap(),
}

urlpatterns = [
    url(r'^page/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),

    url(r'^notice/$',
        NoticeListView.as_view(), name='notice-list'),
    url(r'^notice/(?P<pk>\d+)/$',
        NoticeDetailView.as_view(), name='notice-detail'),

    url(r'^contact/create$',
        ContactCreateView.as_view(), name='contact-create'),
    url(r'^contact/done$',
        ContactDoneView.as_view(), name='contact-done'),

    url(r'^sitemap-notice\.xml$',
        sitemap, {'sitemaps': sitemaps_notice}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-post\.xml$',
        sitemap, {'sitemaps': sitemaps_post}, name='django.contrib.sitemaps.views.sitemap'),
]

voca/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import EntrySitemap
from .views import (
    EntryListView, EntryDetailView,
    LevelListView, EntryLevelListView, EntryLevelDetailView,
    CategoryTemplateView, EntryCategoryView, EntryCategoryDetailView,
    TextbookListView, TextbookEntryListView,
)

app_name = 'voca'

sitemaps_entry = {
    'sitemap': EntrySitemap(),
}

urlpatterns = [
    url(r'^entry/$',
        EntryListView.as_view(), name='entry-list'),
    url(r'^entry/(?P<pk>\d+)/$',
        EntryDetailView.as_view(), name='entry-detail'),

    url(r'^level/$',
        LevelListView.as_view(), name='level-list'),
    url(r'^level/(?P<level>[\w]+)$',
        EntryLevelListView.as_view(), name='level-entry-list'),
    url(r'^level/(?P<level>[\w]+)/(?P<pk>\d+)/$',
        EntryLevelDetailView.as_view(), name='level-entry-detail'),

    url(r'^category/$',
        CategoryTemplateView.as_view(), name='category-list'),
    url(r'^category/(?P<slug>[-\w]+)/$',
        EntryCategoryView.as_view(), name='entry-category'),
    url(r'^category/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        EntryCategoryDetailView.as_view(), name='category-entry-detail'),

    url(r'^textbook/$',
        TextbookListView.as_view(), name='textbook-list'),
    url(r'^textbook/(?P<slug>[-\w]+)/$',
        TextbookEntryListView.as_view(), name='textbook-entry-list'),

    url(r'^sitemap-entry\.xml$',
        sitemap, {'sitemaps': sitemaps_entry}, name='django.contrib.sitemaps.views.sitemap'),
]

help/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import SoftDeletableModel

from rakmai.models import AbstractPage


class Post(SoftDeletableModel, AbstractPage):
    FORMAT_CHOICES = Choices(
        (0, 'html', _('html')),
        (1, 'markdown', _('markdown')),
        (2, 'text', _('text')),
    )

    slug = models.SlugField(
        verbose_name=_('slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        unique=True,
        allow_unicode=True,
    )

    content = models.TextField(
        verbose_name=_('content'),
    )

    markup = models.IntegerField(
        verbose_name=_('markup'),
        choices=FORMAT_CHOICES,
        default=FORMAT_CHOICES.html,
    )

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('help:post-detail', args=[self.slug])


class NoticeMessage(SoftDeletableModel, AbstractPage):
    FORMAT_CHOICES = Choices(
        (0, 'html', _('html')),
        (1, 'markdown', _('markdown')),
        (2, 'text', _('text')),
    )

    CATEGORY_CHOICES = Choices(
        (0, 'common', _('Common')),
    )

    content = models.TextField(
        verbose_name=_('content'),
    )

    markup = models.IntegerField(
        verbose_name=_('markup'),
        choices=FORMAT_CHOICES,
        default=FORMAT_CHOICES.html,
    )

    category = models.IntegerField(
        verbose_name=_('category'),
        choices=CATEGORY_CHOICES,
        default=CATEGORY_CHOICES.common,
        db_index=True,
    )

    class Meta:
        verbose_name = _('notice')
        verbose_name_plural = _('notice')
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('help:notice-detail', args=[self.pk])


class ContactMessage(SoftDeletableModel, AbstractPage):
    fullname = models.CharField(
        verbose_name=_('fullname'),
        max_length=32,
    )

    email = models.EmailField(
        verbose_name=_('email'),
    )

    phone = models.CharField(
        verbose_name=_('phone number'),
        max_length=16,
        blank=True,
        null=True,
    )

    content = models.TextField(
        verbose_name=_('content'),
    )

    user_agent = models.TextField(
        verbose_name=_('user-agent'),
        blank=True,
    )

    accept_language = models.TextField(
        verbose_name=_('accept-language'),
        blank=True,
    )

    ip_address = models.GenericIPAddressField(
        verbose_name=_('IP address'),
    )

    class Meta:
        verbose_name = _('contact')
        verbose_name_plural = _('contact')
        ordering = ['-created']

    def __str__(self):
        return self.title

help/forms.py
import json
import urllib

from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout, Fieldset, Div, Submit, HTML
)
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from .models import ContactMessage


class ContactMessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactMessageForm, self).__init__(*args, **kwargs)

        self.fields['title'].help_text = False

        self.helper = FormHelper()
        self.helper.include_media = False

        fieldset = [
            '',  # Hide the legend of fieldset (HTML tag)
            'title',
            'fullname',
            'email',
            'phone',
            'content',
            HTML('<div class="row">'
                 '<div class="col">'
                 '<div class="g-recaptcha" data-sitekey="{}"></div>'
                 '</div>'
                 '</div>'
                 .format(settings.GOOGLE_RECAPTCHA['site_key'])),
        ]

        self.helper.layout = Layout(
            Fieldset(*fieldset),
            Div(
                Submit('submit', _('Write'), css_class='btn btn-info btn-block'),
                css_class='my-3',
            )
        )

    def clean(self):
        cleaned_data = super(ContactMessageForm, self).clean()

        captcha_response = self.data.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA['secret_key'],
            'response': captcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        captcha_response = urllib.request.urlopen(req)
        result = json.loads(captcha_response.read().decode())

        if not result['success']:
            raise forms.ValidationError(_('Invalid reCAPTCHA. Please try again.'))

        return cleaned_data

    class Media:
        js = ('https://www.google.com/recaptcha/api.js',)

    class Meta:
        model = ContactMessage
        fields = ('title', 'fullname', 'email', 'phone', 'content')

help/views.py
import logging

from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from ipware.ip import get_ip

from rakmai.viewmixins import PageableMixin
from .forms import ContactMessageForm
from .models import (
    Post, NoticeMessage
)
from .viewmixins import HelpContextMixin


class PostDetailView(generic.DetailView):
    logger = logging.getLogger(__name__)
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.select_related('owner')

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['page_title'] = self.object.title
        context['page_meta_description'] = self.object.description
        context['page_meta_keywords'] = self.object.keywords
        return context

    def get_template_names(self):
        return 'help/post_detail.html'


class NoticeListView(PageableMixin, HelpContextMixin, generic.ListView):
    logger = logging.getLogger(__name__)
    context_object_name = 'messages'

    def get_queryset(self):
        return NoticeMessage.objects.all().order_by('-created')

    def get_context_data(self, **kwargs):
        context = super(NoticeListView, self).get_context_data(**kwargs)
        context['page_title'] = _('Notice')
        return context

    def get_template_names(self):
        return 'help/notice_list.html'


class NoticeDetailView(generic.DetailView):
    logger = logging.getLogger(__name__)
    context_object_name = 'post'

    def get_queryset(self):
        return NoticeMessage.objects.select_related('owner')

    def get_context_data(self, **kwargs):
        context = super(NoticeDetailView, self).get_context_data(**kwargs)
        context['page_title'] = _('{} : Notice').format(self.object.title)
        context['page_meta_description'] = self.object.description
        context['page_meta_keywords'] = self.object.keywords
        return context

    def get_template_names(self):
        return 'help/notice_detail.html'


class ContactDoneView(generic.TemplateView):
    logger = logging.getLogger(__name__)

    def get_context_data(self, **kwargs):
        context = super(ContactDoneView, self).get_context_data(**kwargs)
        context['page_title'] = _('Contact Done')
        return context

    def get_template_names(self):
        return 'help/contact_done.html'


class ContactCreateView(generic.CreateView):
    logger = logging.getLogger(__name__)
    form_class = ContactMessageForm

    def get_context_data(self, **kwargs):
        context = super(ContactCreateView, self).get_context_data(**kwargs)
        context['page_title'] = _('Contact')
        return context

    def form_valid(self, form):
        form.instance.updated = now()
        form.instance.ip_address = get_ip(self.request)
        form.instance.accept_language = self.request.META['HTTP_ACCEPT_LANGUAGE']
        form.instance.user_agent = self.request.META['HTTP_USER_AGENT']
        response = super(ContactCreateView, self).form_valid(form)
        return response

    def get_success_url(self):
        return reverse('help:contact-done')

    def get_template_names(self):
        return 'help/contact_create.html'

help/templates/help/contact_create.html
{% extends "rakmai/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h4 class="my-2 my-md-4 text-center">
            문의하기
        </h4>

        <div class="row">
            <div class="col col-md-8 offset-md-2">
                <div class="alert alert-warning py-1">
                    <ul class="mb-0">
                        <li class="my-1">내용 오류 및 버그 신고</li>
                        <li class="my-1">기능 추가 및 개선 요청</li>
                        <li class="my-1">광고 게재 및 제휴 문의</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-8 offset-md-2 mb-3">
                <div class="card rounded-2">
                    <div class="card-body pb-0">
                        {% crispy form %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

help/templates/help/contact_done.html
{% extends "rakmai/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h4 class="my-2 my-md-4 text-center">
            고객문의 접수 완료
        </h4>

        <div class="row">
            <div class="col col-md-8 offset-md-2 mb-3">
                <div class="card rounded-2">
                    <div class="card-body">
                        내용 확인 및 검토 후 연락드리겠습니다. 감사합니다.
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-8 offset-md-2 mb-3">
                <a href="{% url 'home' %}"
                   class="btn btn-block btn-outline-secondary">
                    <i class="fa fa-home fa-fw"></i>
                    홈으로
                </a>
            </div>
        </div>
    </div>
{% endblock %}

help/templates/help/notice_detail.html
{% extends "rakmai/base.html" %}

{% load i18n %}
{% load rakmai_filters %}

{% block content %}
    <div class="container">
        <h4 class="my-2 my-md-4 text-center">{% trans "Notice" %}</h4>

        <div class="row">
            <div class="col mb-1 mb-md-2">
                <div class="card rounded-2">
                    <div class="card-header d-flex flex-wrap">
                        <div class="p-1">
                            <span class="btn btn-sm mr-2 btn-secondary">{{ post.get_category_display }}</span>
                        </div>
                        <div class="p-2">
                            <strong>
                                {% if user.is_superuser %}
                                    <a href="{% url 'admin:help_noticemessage_change' post.id %}">
                                        {{ post.title }}
                                    </a>
                                {% else %}
                                    {{ post.title }}
                                {% endif %}
                            </strong>
                        </div>
                        <div class="p-2 text-muted">
                            {{ post.created|date:'Y.m.d' }}
                        </div>
                    </div>
                    <div class="card-body paragraph help-post pb-0">
                        {% if post.markup == post.FORMAT_CHOICES.html %}
                            {{ post.content|clean_html|linebreaks }}
                        {% elif post.markup == post.FORMAT_CHOICES.markdown %}
                            {{ post.content|markdownify }}
                        {% elif post.markup == post.FORMAT_CHOICES.text %}
                            {{ post.content|strip_html|linebreaks }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'help:notice-list' %}?page={{ request.GET.page }}"
           class="btn btn-outline-secondary btn-block my-2">
            <i class="fa fa-list-ul fa-fw" aria-hidden="true"></i>&nbsp;{% trans "List" %}
        </a>
    </div>
{% endblock %}

help/templates/help/notice_list.html
{% extends "rakmai/base.html" %}

{% load i18n %}
{% load rakmai_filters %}

{% block content %}
    <div class="container">
        <h4 class="my-2 my-md-4 text-center">
            공지사항
        </h4>

        <div class="row">
            <div class="col mb-3">
                <div class="card rounded-2">
                    <ul class="list-group list-group-flush">
                        {% for message in messages %}
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-2 col-md-1 p-md-1 order-1 order-md-1">
                                        <span class="btn btn-sm mr-2 btn-secondary">
                                            {{ message.get_category_display }}
                                        </span>
                                    </div>
                                    <div class="col-12 col-md-9 pt-2 p-md-2 order-3 order-md-2">
                                        <a href="{% url 'help:notice-detail' message.id %}?page={{ page_obj.number }}">
                                            {{ message.title }}
                                        </a>
                                    </div>
                                    <div class="col-10 col-md-2 pt-1 p-md-2 text-md-right text-muted order-2 order-md-3">
                                        {{ message.created|date:'Y.m.d' }}
                                    </div>
                                </div>
                            </li>
                        {% empty %}
                            <li class="list-group-item">
                                {% trans "No message" %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% include './_pagination.html' with page_obj=page_obj page_range=page_range %}
    </div>
{% endblock %}

help/templates/help/post_detail.html
{% extends "rakmai/base.html" %}

{% load rakmai_filters %}

{% block content %}
    <div class="container">
        <h4 class="my-2 my-md-4 text-center">
            {% if user.is_superuser %}
                <a href="{% url 'admin:help_post_change' post.id %}">{{ post.title }}</a>
            {% else %}
                {{ post.title }}
            {% endif %}
        </h4>

        <div class="row">
            <div class="col mb-3">
                <div class="card rounded-2">
                    <div class="card-body paragraph help-post pb-0">
                        {% if post.markup == post.FORMAT_CHOICES.html %}
                            {{ post.content|clean_html|linebreaks }}
                        {% elif post.markup == post.FORMAT_CHOICES.markdown %}
                            {{ post.content|markdownify }}
                        {% elif post.markup == post.FORMAT_CHOICES.text %}
                            {{ post.content|strip_html|linebreaks }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}