book/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    PageSitemap, ArticleSitemap
)
from .views import (
    BookListView, BookDetailView,
    PageDetailView, PageCreateView, PageUpdateView,
    ArticleListView, ArticleDetailView, ArticleCategoryListView, ArticleCreateView, ArticleUpdateView,
)

app_name = 'book'

sitemaps_page = {
    'sitemap': PageSitemap(),
}

sitemaps_article = {
    'sitemap': ArticleSitemap(),
}

urlpatterns = [
    url(r'^$',
        BookListView.as_view(), name='book-list'),
    url(r'^(?P<slug>[-\w]+)/$',
        BookDetailView.as_view(), name='book-detail'),

    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/$',
        PageDetailView.as_view(), name='page-detail'),
    url(r'^(?P<book>[-\w]+)/create$',
        PageCreateView.as_view(), name='page-create'),
    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/update/',
        PageUpdateView.as_view(), name='page-update'),

    url(r'^article/(?P<category>[-\w]+)/$',
        ArticleListView.as_view(), name='article-list'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/$',
        ArticleDetailView.as_view(), name='article-detail'),
    url(r'^article/(?P<category>[-\w]+)/create$',
        ArticleCreateView.as_view(), name='article-create'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/update/',
        ArticleUpdateView.as_view(), name='article-update'),
    url(r'^article/(?P<category>[-\w]+)/category/(?P<slug>[-\w]+)$',
        ArticleCategoryListView.as_view(), name='article-category-list'),

    url(r'^sitemap-page\.xml$',
        sitemap, {'sitemaps': sitemaps_page}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-article\.xml$',
        sitemap, {'sitemaps': sitemaps_article}, name='django.contrib.sitemaps.views.sitemap'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin

from rakmai.views import HomeView

urlpatterns = [
    url(r'^$',
        HomeView.as_view(), name='home'),
    url(r'{}'.format(settings.ADMIN_URL),
        admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^voca/', include('voca.urls', namespace='voca')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^help/', include('help.urls', namespace='help')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.GOOGLE_OTP_ENABLED:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite

help/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    NoticeSitemap, PostSitemap
)
from .views import (
    PostDetailView, NoticeDetailView, NoticeListView,
    ContactCreateView, ContactDoneView,
)

app_name = 'help'

sitemaps_notice = {
    'sitemap': NoticeSitemap(),
}

sitemaps_post = {
    'sitemap': PostSitemap(),
}

urlpatterns = [
    url(r'^page/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),

    url(r'^notice/$',
        NoticeListView.as_view(), name='notice-list'),
    url(r'^notice/(?P<pk>\d+)/$',
        NoticeDetailView.as_view(), name='notice-detail'),

    url(r'^contact/create$',
        ContactCreateView.as_view(), name='contact-create'),
    url(r'^contact/done$',
        ContactDoneView.as_view(), name='contact-done'),

    url(r'^sitemap-notice\.xml$',
        sitemap, {'sitemaps': sitemaps_notice}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-post\.xml$',
        sitemap, {'sitemaps': sitemaps_post}, name='django.contrib.sitemaps.views.sitemap'),
]

voca/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import EntrySitemap
from .views import (
    EntryListView, EntryDetailView,
    LevelListView, EntryLevelListView, EntryLevelDetailView,
    CategoryTemplateView, EntryCategoryView, EntryCategoryDetailView,
    TextbookListView, TextbookEntryListView,
)

app_name = 'voca'

sitemaps_entry = {
    'sitemap': EntrySitemap(),
}

urlpatterns = [
    url(r'^entry/$',
        EntryListView.as_view(), name='entry-list'),
    url(r'^entry/(?P<pk>\d+)/$',
        EntryDetailView.as_view(), name='entry-detail'),

    url(r'^level/$',
        LevelListView.as_view(), name='level-list'),
    url(r'^level/(?P<level>[\w]+)$',
        EntryLevelListView.as_view(), name='level-entry-list'),
    url(r'^level/(?P<level>[\w]+)/(?P<pk>\d+)/$',
        EntryLevelDetailView.as_view(), name='level-entry-detail'),

    url(r'^category/$',
        CategoryTemplateView.as_view(), name='category-list'),
    url(r'^category/(?P<slug>[-\w]+)/$',
        EntryCategoryView.as_view(), name='entry-category'),
    url(r'^category/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        EntryCategoryDetailView.as_view(), name='category-entry-detail'),

    url(r'^textbook/$',
        TextbookListView.as_view(), name='textbook-list'),
    url(r'^textbook/(?P<slug>[-\w]+)/$',
        TextbookEntryListView.as_view(), name='textbook-entry-list'),

    url(r'^sitemap-entry\.xml$',
        sitemap, {'sitemaps': sitemaps_entry}, name='django.contrib.sitemaps.views.sitemap'),
]

voca/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import (
    TimeStampedModel, SoftDeletableModel
)
from mptt.fields import TreeForeignKey

from rakmai.models import AbstractCategory


class Entry(SoftDeletableModel, TimeStampedModel):
    LEVEL_CHOICES = Choices(
        (0, 'beginner', _('beginner')),
        (1, 'intermediate', _('intermediate')),
        (2, 'advanced', _('advanced')),
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=255,
        null=False,
        blank=False,
        db_index=True,
    )

    pronunciation = models.CharField(
        verbose_name=_('pronunciation'),
        max_length=250,
    )

    description = models.TextField(
        verbose_name=_('description'),
        blank=True,
    )

    level = models.IntegerField(
        verbose_name=_('level'),
        choices=LEVEL_CHOICES,
        default=LEVEL_CHOICES.beginner,
        db_index=True,
    )

    categories = models.ManyToManyField(
        'voca.EntryCategory',
        through='voca.EntryCategoryMembership',
        blank=True,
        symmetrical=False,
    )

    components = models.ManyToManyField(
        'self',
        through='voca.EntryCompound',
        blank=True,
        symmetrical=False,
    )

    class Meta:
        verbose_name = _('entry')
        verbose_name_plural = _('entries')

    def __str__(self):
        return self.title


class EntryCompound(models.Model):
    from_entry = models.ForeignKey(
        'voca.Entry',
        related_name='from_entry',
        db_index=True,
        on_delete=models.CASCADE,
    )

    to_entry = models.ForeignKey(
        'voca.Entry',
        verbose_name=_('compound word'),
        related_name='to_entry',
        db_index=True,
        on_delete=models.CASCADE,
    )

    position = models.IntegerField(
        verbose_name=_('position'),
    )

    class Meta:
        verbose_name = _('compound word')
        verbose_name_plural = _('compound words')
        ordering = ('position',)


class EntryMeaning(TimeStampedModel):
    PART_CHOICES = Choices(
        (0, 'noun', _('noun')),
        (1, 'pronoun', _('pronoun')),
        (2, 'verb', _('verb')),
        (3, 'modifier', _('modifier')),
        (4, 'preposition', _('preposition')),
        (5, 'conjunction', _('conjunction')),
        (6, 'interjection', _('interjection')),
        (7, 'classifier', _('classifier')),
    )

    part = models.IntegerField(
        verbose_name=_('part of speech'),
        choices=PART_CHOICES,
        default=PART_CHOICES.noun,
        db_index=True,
    )

    entry = models.ForeignKey(
        'voca.Entry',
        verbose_name=_('entry'),
        related_name='meanings',
        on_delete=models.CASCADE,
    )

    meaning = models.CharField(
        verbose_name=_('meaning'),
        max_length=250,
    )

    position = models.IntegerField(
        verbose_name=_('position'),
    )

    class Meta:
        verbose_name = _('meaning')
        verbose_name_plural = _('meanings')
        ordering = ['position']

    def __str__(self):
        return '{} {}'.format(self.entry.title, self.meaning)


class EntryCategory(AbstractCategory):
    description = models.TextField(
        verbose_name=_('description'),
        blank=True,
    )

    class Meta:
        verbose_name = _('entry category')
        verbose_name_plural = _('entry categories')

    def __str__(self):
        return self.title


class EntryCategoryMembership(models.Model):
    entry = models.ForeignKey(
        'voca.Entry',
        db_index=True,
        on_delete=models.CASCADE,
    )

    category = TreeForeignKey(
        'voca.EntryCategory',
        verbose_name=_('entry category'),
        null=True,
        blank=True,
        db_index=True,
        on_delete=models.CASCADE,
    )

    position = models.IntegerField(
        verbose_name=_('position'),
    )

    class Meta:
        verbose_name = _('category membership')
        verbose_name_plural = _('category memberships')
        ordering = ['position']


class EntrySentence(SoftDeletableModel, TimeStampedModel):
    title = models.CharField(
        verbose_name=_('title'),
        max_length=255,
        null=False,
        blank=False,
        db_index=True,
    )

    pronunciation = models.CharField(
        verbose_name=_('pronunciation'),
        max_length=250,
    )

    meaning = models.TextField(
        verbose_name=_('meaning'),
        blank=True,
    )

    words = models.ManyToManyField(
        'voca.Entry',
        through='voca.EntrySentenceCompound',
        blank=True,
        symmetrical=False,
    )

    class Meta:
        verbose_name = _('entry sentence')
        verbose_name_plural = _('entry sentences')

    def __str__(self):
        return self.title


class EntrySentenceCompound(models.Model):
    from_sentence = models.ForeignKey(
        'voca.EntrySentence',
        db_index=True,
        on_delete=models.CASCADE,
    )

    to_entry = models.ForeignKey(
        'voca.Entry',
        db_index=True,
        on_delete=models.CASCADE,
    )

    position = models.IntegerField(
        verbose_name=_('position'),
    )

    class Meta:
        verbose_name = _('word')
        verbose_name_plural = _('words')
        ordering = ['position']


class Textbook(TimeStampedModel):
    STATUS_CHOICES = Choices(
        (0, 'public', _('public')),
        (1, 'private', _('private')),
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=255,
        null=False,
        blank=False,
        db_index=True,
    )

    slug = models.SlugField(
        verbose_name=_('slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        unique=True,
        allow_unicode=True,
    )

    author = models.CharField(
        verbose_name=_('author'),
        max_length=255,
    )

    publisher = models.CharField(
        verbose_name=_('publisher'),
        max_length=255,
    )

    position = models.IntegerField(
        verbose_name=_('position'),
    )

    words = models.ManyToManyField(
        'voca.Entry',
        through='voca.EntryTextbookCompound',
        blank=True,
        symmetrical=False,
    )

    chapter = models.IntegerField(
        verbose_name=_('chapter'),
    )

    status = models.IntegerField(
        verbose_name=_('status'),
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.public,
        db_index=True,
    )

    class Meta:
        verbose_name = _('textbook')
        verbose_name_plural = _('textbooks')
        ordering = ['position', ]

    def __str__(self):
        return self.title


class EntryTextbookCompound(models.Model):
    textbook = models.ForeignKey(
        'voca.Textbook',
        verbose_name=_('textbook'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    entry = models.ForeignKey(
        'voca.Entry',
        verbose_name=_('entry'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    chapter = models.IntegerField(
        verbose_name=_('chapter'),
    )

    page = models.IntegerField(
        verbose_name=_('page'),
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _('textbook word')
        verbose_name_plural = _('textbook words')
        ordering = ['chapter', 'page']

voca/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import (
    EntryTextbookCompound, EntryMeaning
)


class VocabularySearchForm(forms.Form):
    q = forms.CharField(
        label=_('lookup word'),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('lookup word'),
                'required': 'True',
            }
        )
    )

    def __init__(self, *args, **kwargs):
        q = kwargs.pop('q', '')

        super(VocabularySearchForm, self).__init__(*args, **kwargs)

        self.fields['q'].initial = q


class TextbookFilterForm(forms.Form):
    chapter = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'required': 'True',
            }
        )
    )

    def __init__(self, *args, **kwargs):
        slug = kwargs.pop('slug', '')
        chapter = kwargs.pop('chapter', '1')

        super(TextbookFilterForm, self).__init__(*args, **kwargs)

        chapters = EntryTextbookCompound.objects \
            .filter(textbook__slug=slug) \
            .order_by('chapter') \
            .values_list('chapter', flat=True) \
            .distinct()

        self.fields['chapter'].choices = list(map(lambda x: (str(x), str(x) + '과'), chapters))
        self.fields['chapter'].initial = chapter


class PartFilterForm(forms.Form):
    part = forms.ChoiceField(
        choices=EntryMeaning.PART_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'required': 'True',
            }
        )
    )

    def __init__(self, *args, **kwargs):
        part = kwargs.pop('part', 0)
        super(PartFilterForm, self).__init__(*args, **kwargs)
        self.fields['part'].initial = part

voca/templates/voca/category_entry_detail.html
{% extends "./2_columns.html" %}
{% load i18n %}
{% load voca_tags %}

{% block main_content %}
    <div class="row my-2 mt-md-4">
        <div class="col-md-2">
            <h4 class="mt-md-2">
                <a href="{% url 'voca:category-list' %}">
                    {% trans "Vocabulary" %}
                </a>
            </h4>
        </div>
        <div class="col-md-10">
            <form action="{% url 'voca:entry-category' category_slug %}" method="get" class="input-group mt-md-1">
                {{ search_form.q }}
                <span class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </form>
        </div>
    </div>

    {% get_category_ancestor_path category_slug as breadcrumbs %}
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb my-1 mb-md-2 py-1">
                    <li class="breadcrumb-item">
                        <a href="{% url 'voca:category-list' %}">{% trans "All Categories" %}</a>
                    </li>
                    {% for crumb in breadcrumbs %}
                        {% if not forloop.last %}
                            <li class="breadcrumb-item">
                                <a href="{% url 'voca:entry-category' crumb.slug %}">
                                    {{ crumb.title }}
                                </a>
                            </li>
                        {% else %}
                            {% if user.is_superuser %}
                                <li class="breadcrumb-item active">
                                    <a href="{% url 'admin:voca_entrycategory_change' crumb.id %}">
                                        {{ crumb.title }}
                                    </a>
                                </li>
                            {% else %}
                                <li class="breadcrumb-item active">{{ crumb.title }}</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ol>
            </nav>
        </div>
    </div>

    <div class="row my-2">
        <div class="col thai-font">
            <strong>
                {% if user.is_superuser %}
                    <a href="{% url 'admin:voca_entry_change' entry.id %}">{{ entry.title }}</a>
                {% else %}
                    {{ entry.title }}
                {% endif %}
            </strong>
        </div>
    </div>

    <div class="row my-2 pb-1">
        <div class="col-md-2">발음</div>
        <div class="col-md-10 thai-font">{{ entry.pronunciation }}</div>
        <div class="col-12">
            <hr class="my-0">
        </div>
    </div>
    {% for meaning in entry.meanings.all %}
        <div class="row my-2">
            <div class="col-md-2">{{ meaning.get_part_display }}</div>
            <div class="col-md-10">{{ meaning.meaning }}</div>
            {% if forloop.last %}
                <div class="col-12">
                    <hr class="mt-1 mb-2">
                </div>
            {% endif %}
        </div>
    {% endfor %}
    {% if entry.description %}
        <div class="row my-2">
            <div class="col-md-2">{% trans "description" %}</div>
            <div class="col-md-10 thai-font">{{ entry.description }}</div>
        </div>
    {% endif %}
    {% for component in entry_components %}
        {% if forloop.first %}
            <div class="row mt-4 mb-1 mb-md-3">
                <div class="col"><strong>형태소</strong></div>
            </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-md-5 thai-font">
                <a href="{% url 'voca:category-entry-detail' category_slug component.pk %}?page={{ request.GET.page }}&part={{ request.GET.part }}">
                    {{ component.title }}
                </a>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled mb-0">
                    {% for meaning in component.meanings.all %}
                        <li class="mb-2">{{ meaning.get_part_display }} - {{ meaning.meaning }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-12">
                <hr class="my-0">
            </div>
        </div>
    {% endfor %}

    {% for word in entry_complex_words %}
        {% if forloop.first %}
            <div class="row mt-4 mb-1 mb-md-3">
                <div class="col"><strong>파생어 / 합성어</strong></div>
            </div>
        {% endif %}
        <div class="row pb-1{% if forloop.last %} mb-1 mb-md-3{% endif %}">
            {% if not forloop.first %}
                <div class="col-12">
                    <hr class="mt-1">
                </div>
            {% endif %}
            <div class="col-md-5 thai-font">
                <a href="{% url 'voca:category-entry-detail' category_slug word.from_entry.id %}?page={{ request.GET.page }}&part={{ request.GET.part }}">
                    {{ word.from_entry.title }}
                </a>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled mb-0">
                    {% for meaning in word.from_entry.meanings.all %}
                        <li class="mb-2">{{ meaning.get_part_display }} - {{ meaning.meaning }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

    {% for sentence in entry_sentences %}
        {% if forloop.first %}
            <div class="row mt-4 mb-2">
                <div class="col">예문</div>
            </div>
        {% endif %}
        <div class="row mt-2 mb-0">
            <div class="col thai-font">
                {% for word in sentence.entrysentencecompound_set.all %}
                    <a href="{% url 'voca:category-entry-detail' category_slug word.to_entry.id %}?page={{ request.GET.page }}&part={{ request.GET.part }}">
                        {{ word.to_entry.title }}
                    </a>{% endfor %}
            </div>
        </div>
        <div class="row my-0">
            <div class="col">
                {{ sentence.meaning }}
            </div>
        </div>
    {% endfor %}
    <div class="row my-1 my-md-3">
        <div class="col">
            <a href="{% url 'voca:entry-category' category_slug %}?page={{ request.GET.page }}&part={{ request.GET.part }}"
               class="btn btn-secondary">
                {% trans "List" %}
            </a>
        </div>
    </div>
{% endblock %}

voca/templates/voca/category_entry_list.html
{% extends "./2_columns.html" %}
{% load i18n %}
{% load voca_tags %}

{% block main_content %}
    <div class="row my-2 mt-md-4">
        <div class="col-md-2">
            <h4 class="mt-md-2">
                <a href="{% url 'voca:category-list' %}">
                    {% trans "Vocabulary" %}
                </a>
            </h4>
        </div>
        <div class="col-md-10">
            <form action="{% url 'voca:entry-list' %}" method="get" class="input-group mt-md-1">
                {{ search_form.q }}
                <span class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </form>
        </div>
    </div>

    {% get_category_ancestor_path category_slug as breadcrumbs %}
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mt-1 mb-2 mb-md-3 py-1">
                    <li class="breadcrumb-item">
                        <a href="{% url 'voca:category-list' %}">{% trans "All Categories" %}</a>
                    </li>
                    {% for crumb in breadcrumbs %}
                        {% if not forloop.last %}
                            <li class="breadcrumb-item">
                                <a href="{% url 'voca:entry-category' crumb.slug %}">
                                    {{ crumb.title }}
                                </a>
                            </li>
                        {% else %}
                            {% if user.is_superuser %}
                                <li class="breadcrumb-item active">
                                    <a href="{% url 'admin:voca_entrycategory_change' crumb.id %}">
                                        {{ crumb.title }}
                                    </a>
                                </li>
                            {% else %}
                                <li class="breadcrumb-item active">{{ crumb.title }}</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ol>
            </nav>
        </div>
    </div>

    {% for entry in entries %}
        <div class="row pb-1{% if forloop.last %} mb-1 mb-md-3{% endif %}">
            {% if not forloop.first %}
                <div class="col-12">
                    <hr class="mt-1">
                </div>
            {% endif %}
            <div class="col-md-5 thai-font">
                <a href="{% url 'voca:category-entry-detail' category_slug entry.pk %}?page={{ request.GET.page }}">
                    {{ entry.title }}
                </a>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled mb-0">
                    {% for meaning in entry.meanings.all %}
                        <li{% if not forloop.last %} class="mb-2"{% endif %}>
                            {{ meaning.get_part_display }} - {{ meaning.meaning }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
    <!-- Pagination -->
    {% include './_pagination_category.html' with page_obj=page_obj page_range=page_range %}
{% endblock %}

voca/templates/voca/level_entry_detail.html
{% extends "./2_columns.html" %}
{% load i18n %}

{% block main_content %}
    <div class="row my-2 my-md-4">
        <div class="col-md-2">
            <h4 class="mt-md-2">
                <a href="{% url 'voca:category-list' %}">
                    {% trans "Vocabulary" %}
                </a>
            </h4>
        </div>
        <div class="col-md-10">
            <form action="{% url 'voca:entry-list' %}" method="get" class="input-group mt-md-1">
                {{ search_form.q }}
                <span class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </form>
        </div>
    </div>

    <div class="row my-2">
        <div class="col thai-font">
            <strong>
                {% if user.is_superuser %}
                    <a href="{% url 'admin:voca_entry_change' entry.id %}">{{ entry.title }}</a>
                {% else %}
                    {{ entry.title }}
                {% endif %}
            </strong>
        </div>
    </div>

    <div class="row my-2 pb-1">
        <div class="col-md-2">발음</div>
        <div class="col-md-10 thai-font">{{ entry.pronunciation }}</div>
        <div class="col-12">
            <hr class="my-0">
        </div>
    </div>
    {% for meaning in entry.meanings.all %}
        <div class="row my-2">
            <div class="col-md-2">{{ meaning.get_part_display }}</div>
            <div class="col-md-10">{{ meaning.meaning }}</div>
            {% if forloop.last %}
                <div class="col-12">
                    <hr class="mt-1 mb-2">
                </div>
            {% endif %}
        </div>
    {% endfor %}
    {% if entry.description %}
        <div class="row my-2">
            <div class="col-md-2">{% trans "description" %}</div>
            <div class="col-md-10 thai-font">{{ entry.description }}</div>
        </div>
    {% endif %}
    {% for component in entry_components %}
        {% if forloop.first %}
            <div class="row mt-4 mb-1 mb-md-3">
                <div class="col"><strong>형태소</strong></div>
            </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-md-5 thai-font">
                <a href="{% url 'voca:level-entry-detail' level component.pk %}?page={{ request.GET.page }}&part={{ request.GET.part }}">
                    {{ component.title }}
                </a>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled mb-0">
                    {% for meaning in component.meanings.all %}
                        <li class="mb-2">{{ meaning.get_part_display }} - {{ meaning.meaning }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-12">
                <hr class="my-0">
            </div>
        </div>
    {% endfor %}

    {% for word in entry_complex_words %}
        {% if forloop.first %}
            <div class="row mt-4 mb-1 mb-md-3">
                <div class="col"><strong>파생어 / 합성어</strong></div>
            </div>
        {% endif %}
        <div class="row pb-1{% if forloop.last %} mb-1 mb-md-3{% endif %}">
            {% if not forloop.first %}
                <div class="col-12">
                    <hr class="mt-1">
                </div>
            {% endif %}
            <div class="col-md-5 thai-font">
                <a href="{% url 'voca:level-entry-detail' level word.from_entry.id %}?page={{ request.GET.page }}&part={{ request.GET.part }}">
                    {{ word.from_entry.title }}
                </a>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled mb-0">
                    {% for meaning in word.from_entry.meanings.all %}
                        <li class="mb-2">{{ meaning.get_part_display }} - {{ meaning.meaning }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

    {% for sentence in entry_sentences %}
        {% if forloop.first %}
            <div class="row mt-4 mb-2">
                <div class="col">예문</div>
            </div>
        {% endif %}
        <div class="row mt-2 mb-0">
            <div class="col thai-font">
                {% for word in sentence.entrysentencecompound_set.all %}
                    <a href="{% url 'voca:level-entry-detail' level word.to_entry.id %}?page={{ request.GET.page }}&part={{ request.GET.part }}">
                        {{ word.to_entry.title }}
                    </a>{% endfor %}
            </div>
        </div>
        <div class="row my-0">
            <div class="col">
                {{ sentence.meaning }}
            </div>
        </div>
    {% endfor %}
    <div class="row mt-1 mt-md-4">
        <div class="col">
            <a href="{% url 'voca:level-entry-list' level %}?page={{ request.GET.page }}&part={{ request.GET.part }}"
               class="btn btn-secondary">
                {% trans "List" %}
            </a>
        </div>
    </div>
{% endblock %}