book/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    PageSitemap, ArticleSitemap
)
from .views import (
    BookListView, BookDetailView,
    PageDetailView, PageCreateView, PageUpdateView,
    ArticleListView, ArticleDetailView, ArticleCategoryListView, ArticleCreateView, ArticleUpdateView,
)

app_name = 'book'

sitemaps_page = {
    'sitemap': PageSitemap(),
}

sitemaps_article = {
    'sitemap': ArticleSitemap(),
}

urlpatterns = [
    url(r'^$',
        BookListView.as_view(), name='book-list'),
    url(r'^(?P<slug>[-\w]+)/$',
        BookDetailView.as_view(), name='book-detail'),

    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/$',
        PageDetailView.as_view(), name='page-detail'),
    url(r'^(?P<book>[-\w]+)/create$',
        PageCreateView.as_view(), name='page-create'),
    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/update/',
        PageUpdateView.as_view(), name='page-update'),

    url(r'^article/(?P<category>[-\w]+)/$',
        ArticleListView.as_view(), name='article-list'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/$',
        ArticleDetailView.as_view(), name='article-detail'),
    url(r'^article/(?P<category>[-\w]+)/create$',
        ArticleCreateView.as_view(), name='article-create'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/update/',
        ArticleUpdateView.as_view(), name='article-update'),
    url(r'^article/(?P<category>[-\w]+)/category/(?P<slug>[-\w]+)$',
        ArticleCategoryListView.as_view(), name='article-category-list'),

    url(r'^sitemap-page\.xml$',
        sitemap, {'sitemaps': sitemaps_page}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-article\.xml$',
        sitemap, {'sitemaps': sitemaps_article}, name='django.contrib.sitemaps.views.sitemap'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin

from rakmai.views import HomeView

urlpatterns = [
    url(r'^$',
        HomeView.as_view(), name='home'),
    url(r'{}'.format(settings.ADMIN_URL),
        admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^voca/', include('voca.urls', namespace='voca')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^help/', include('help.urls', namespace='help')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.GOOGLE_OTP_ENABLED:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite

help/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    NoticeSitemap, PostSitemap
)
from .views import (
    PostDetailView, NoticeDetailView, NoticeListView,
    ContactCreateView, ContactDoneView,
)

app_name = 'help'

sitemaps_notice = {
    'sitemap': NoticeSitemap(),
}

sitemaps_post = {
    'sitemap': PostSitemap(),
}

urlpatterns = [
    url(r'^page/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),

    url(r'^notice/$',
        NoticeListView.as_view(), name='notice-list'),
    url(r'^notice/(?P<pk>\d+)/$',
        NoticeDetailView.as_view(), name='notice-detail'),

    url(r'^contact/create$',
        ContactCreateView.as_view(), name='contact-create'),
    url(r'^contact/done$',
        ContactDoneView.as_view(), name='contact-done'),

    url(r'^sitemap-notice\.xml$',
        sitemap, {'sitemaps': sitemaps_notice}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-post\.xml$',
        sitemap, {'sitemaps': sitemaps_post}, name='django.contrib.sitemaps.views.sitemap'),
]

voca/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import EntrySitemap
from .views import (
    EntryListView, EntryDetailView,
    LevelListView, EntryLevelListView, EntryLevelDetailView,
    CategoryTemplateView, EntryCategoryView, EntryCategoryDetailView,
    TextbookListView, TextbookEntryListView,
)

app_name = 'voca'

sitemaps_entry = {
    'sitemap': EntrySitemap(),
}

urlpatterns = [
    url(r'^entry/$',
        EntryListView.as_view(), name='entry-list'),
    url(r'^entry/(?P<pk>\d+)/$',
        EntryDetailView.as_view(), name='entry-detail'),

    url(r'^level/$',
        LevelListView.as_view(), name='level-list'),
    url(r'^level/(?P<level>[\w]+)$',
        EntryLevelListView.as_view(), name='level-entry-list'),
    url(r'^level/(?P<level>[\w]+)/(?P<pk>\d+)/$',
        EntryLevelDetailView.as_view(), name='level-entry-detail'),

    url(r'^category/$',
        CategoryTemplateView.as_view(), name='category-list'),
    url(r'^category/(?P<slug>[-\w]+)/$',
        EntryCategoryView.as_view(), name='entry-category'),
    url(r'^category/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        EntryCategoryDetailView.as_view(), name='category-entry-detail'),

    url(r'^textbook/$',
        TextbookListView.as_view(), name='textbook-list'),
    url(r'^textbook/(?P<slug>[-\w]+)/$',
        TextbookEntryListView.as_view(), name='textbook-entry-list'),

    url(r'^sitemap-entry\.xml$',
        sitemap, {'sitemaps': sitemaps_entry}, name='django.contrib.sitemaps.views.sitemap'),
]

book/models.py
import uuid

from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from easy_thumbnails.fields import ThumbnailerImageField
from model_utils import Choices
from model_utils.models import (
    TimeStampedModel
)
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from rakmai.models import (
    AbstractAttachment, AbstractCategory, AbstractPage
)


def upload_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/book/<today>/<uuid>.<ext>
    return 'book/{}/{}.{}'.format(now().strftime('%Y-%m-%d'), uuid.uuid4(), filename.split('.')[-1])


class Book(TimeStampedModel):
    STATUS_CHOICES = Choices(
        (0, 'public', _('public')),
        (1, 'private', _('private')),
    )

    LICENSE_CHOICES = Choices(
        (0, 'BY', _('BY')),
        (1, 'BY-SA', _('BY-SA')),
        (2, 'BY-ND', _('BY-ND')),
        (3, 'BY-NC', _('BY-NC')),
        (4, 'BY-NC-SA', _('BY-NC-SA')),
        (5, 'BY-NC-ND', _('BY-NC-ND')),
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=250,
    )

    slug = models.SlugField(
        verbose_name=_('slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        unique=True,
        allow_unicode=True,
    )

    description = models.TextField(
        verbose_name=_('description'),
        blank=True,
    )

    category = TreeForeignKey(
        'book.Category',
        verbose_name=_('category'),
        null=True,
        blank=True,
        db_index=True,
        on_delete=models.SET_NULL,
    )

    thumbnail = ThumbnailerImageField(
        verbose_name=_('thumbnail'),
        upload_to=upload_directory_path,
        blank=True,
    )

    status = models.IntegerField(
        verbose_name=_('status'),
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.public,
        db_index=True,
    )

    license = models.IntegerField(
        verbose_name=_('license'),
        choices=LICENSE_CHOICES,
        default=LICENSE_CHOICES.BY,
        db_index=True,
    )

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('owner'),
        null=True,
        blank=True,
        editable=True,
        on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_owned",
    )

    view_count = models.PositiveIntegerField(
        verbose_name=_('view count'),
        default=0,
    )

    updated = models.DateTimeField(
        verbose_name=_('updated date'),
        null=True,
    )

    position = models.PositiveIntegerField(
        verbose_name=_('position'),
        default=1,
    )

    class Meta:
        verbose_name = _('book')
        verbose_name_plural = _('books')
        ordering = ['position', '-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book:book-detail', args=[self.pk])


class Attachment(AbstractAttachment):
    file = models.FileField(
        verbose_name=_('uploaded file'),
        upload_to=upload_directory_path,
        storage=default_storage,
    )

    page = models.ForeignKey(
        'book.Page',
        verbose_name=_('page'),
        related_name='attachments',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = _('attachment')
        verbose_name_plural = _('attachments')


class Category(AbstractCategory):
    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return self.title


class Page(MPTTModel, AbstractPage):
    STATUS_CHOICES = Choices(
        (0, 'draft', _('draft')),
        (1, 'public', _('public')),
        (2, 'private', _('private')),
    )

    content = models.TextField(
        verbose_name=_('content'),
    )

    content1 = models.TextField(
        verbose_name=_('content1'),
        blank=True,
    )

    content2 = models.TextField(
        verbose_name=_('content2'),
        blank=True,
    )

    image = ThumbnailerImageField(
        verbose_name=_('image'),
        upload_to=upload_directory_path,
        blank=True,
    )

    youtube = models.URLField(
        verbose_name=_('youtube'),
        blank=True,
    )

    book = models.ForeignKey(
        'book.Book',
        verbose_name=_('book'),
        related_name='pages',
        db_index=True,
        on_delete=models.CASCADE,
    )

    parent = TreeForeignKey(
        'self',
        verbose_name=_('parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True,
        on_delete=models.SET_NULL,
    )

    status = models.IntegerField(
        verbose_name=_('status'),
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.public,
        db_index=True,
    )

    view_count = models.PositiveIntegerField(
        verbose_name=_('view count'),
        default=0,
    )

    ip_address = models.GenericIPAddressField(
        verbose_name=_('IP address'),
    )

    updated = models.DateTimeField(
        verbose_name=_('updated date'),
        null=True,
    )

    class Meta:
        verbose_name = _('page')
        verbose_name_plural = _('pages')
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book:page-detail', args=[self.book.pk, self.pk])


class ArticleCategory(AbstractCategory):
    class Meta:
        verbose_name = _('article category')
        verbose_name_plural = _('article categories')

    def __str__(self):
        return self.title


class Article(AbstractPage):
    STATUS_CHOICES = Choices(
        (0, 'draft', _('draft')),
        (1, 'public', _('public')),
        (2, 'private', _('private')),
    )

    category = TreeForeignKey(
        'book.ArticleCategory',
        verbose_name=_('article category'),
        null=True,
        blank=True,
        db_index=True,
        on_delete=models.SET_NULL,
    )

    content = models.TextField(
        verbose_name=_('content'),
    )

    content1 = models.TextField(
        verbose_name=_('content1'),
        blank=True,
    )

    content2 = models.TextField(
        verbose_name=_('content2'),
        blank=True,
    )

    words = models.ManyToManyField(
        'voca.Entry',
        through='book.EntryArticleMembership',
        blank=True,
        symmetrical=False,
    )

    image = ThumbnailerImageField(
        verbose_name=_('image'),
        upload_to=upload_directory_path,
        blank=True,
    )

    youtube = models.URLField(
        verbose_name=_('youtube'),
        blank=True,
    )

    status = models.IntegerField(
        verbose_name=_('status'),
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.public,
        db_index=True,
    )

    view_count = models.PositiveIntegerField(
        verbose_name=_('view count'),
        default=0,
    )

    ip_address = models.GenericIPAddressField(
        verbose_name=_('IP address'),
    )

    updated = models.DateTimeField(
        verbose_name=_('updated date'),
        null=True,
    )

    class Meta:
        verbose_name = _('article')
        verbose_name_plural = _('articles')
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book:article-detail', args=[self.category.slug, self.pk])


class EntryArticleMembership(models.Model):
    from_article = models.ForeignKey(
        'book.Article',
        db_index=True,
        on_delete=models.CASCADE,
    )

    to_entry = models.ForeignKey(
        'voca.Entry',
        db_index=True,
        on_delete=models.CASCADE,
    )

    position = models.IntegerField(
        verbose_name=_('position'),
    )

    class Meta:
        verbose_name = _('word')
        verbose_name_plural = _('words')
        ordering = ['position']

book/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout, Fieldset, Div, Submit, HTML
)
from django import forms
from django.utils.translation import ugettext_lazy as _
from mptt.forms import TreeNodeChoiceField

from .models import (
    Page, Article
)


class PageForm(forms.ModelForm):
    parent = TreeNodeChoiceField(None)

    def __init__(self, *args, **kwargs):
        self.parent_queryset = kwargs.pop('parent_queryset', None)

        super(PageForm, self).__init__(*args, **kwargs)

        self.fields['parent'].queryset = self.parent_queryset
        self.fields['parent'].required = False
        self.fields['parent'].label = _('parent')

        self.helper = FormHelper()
        self.helper.include_media = False

        # horizontal grid form
        self.helper.form_class = 'form-horizontal'  # Appends `row` class to `div` surrounding label and form field
        self.helper.label_class = 'col-2 col-form-label'
        self.helper.field_class = 'col-10'

        fieldset = [
            '',  # Hide the legend of fieldset (HTML tag)
            'status',
            'title',
            'parent',
            'content',
            'content1',
            'content2',
            'image',
            'youtube',
            'keywords',
            'description',
        ]

        self.helper.layout = Layout(
            Fieldset(*fieldset),
            HTML('''
            <div class="my-3">
            <button name="submit" class="btn btn-primary btn btn-info btn-block" type="submit">
                <i class="fa fa-pencil fa-fw"></i>
                {}
            </button>
            </div>'''.format(_('Write'))),
        )

    class Meta:
        model = Page
        fields = ('title', 'parent', 'image', 'youtube', 'content', 'content1', 'content2',
                  'keywords', 'description', 'status')


class ArticleForm(forms.ModelForm):
    category = TreeNodeChoiceField(None)

    def __init__(self, *args, **kwargs):
        self.category_queryset = kwargs.pop('category_queryset', None)

        super(ArticleForm, self).__init__(*args, **kwargs)

        self.fields['category'].queryset = self.category_queryset
        self.fields['category'].required = False
        self.fields['category'].label = _('category')

        self.helper = FormHelper()
        self.helper.include_media = False

        # horizontal grid form
        self.helper.form_class = 'form-horizontal'  # Appends `row` class to `div` surrounding label and form field
        self.helper.label_class = 'col-2 col-form-label'
        self.helper.field_class = 'col-10'

        fieldset = [
            '',  # Hide the legend of fieldset (HTML tag)
            'status',
            'title',
            'category',
            'content',
            'content1',
            'content2',
            'image',
            'youtube',
            'keywords',
            'description',
        ]

        self.helper.layout = Layout(
            Fieldset(*fieldset),
            Div(
                Submit('submit', _('Write'), css_class='btn btn-info btn-block'),
                css_class='my-3',
            )
        )

    class Meta:
        model = Article
        fields = ('title', 'category', 'image', 'youtube', 'content', 'content1', 'content2',
                  'keywords', 'description', 'status')

book/templates/book/2_columns.html
{% extends "rakmai/base.html" %}
{% load i18n %}
{% load book_tags %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Sidebar Widgets Column -->
            <div class="col-12 col-md-4">
                <div class="card my-2 my-md-4">
                    <h5 class="card-header">
                        {% if request.user.is_superuser %}
                            <a href="{% url 'admin:book_book_change' book.id %}">
                                {{ book.title }}
                            </a>
                        {% else %}
                            <a href="{% url 'book:book-detail' book.id %}">
                                {{ book.title }}
                            </a>
                        {% endif %}
                    </h5>
                    <div class="card-body py-1">
                        <h5 class="card-title text-center mb-1">목차</h5>
                        {% if request.user.is_superuser %}
                            <a href="{% url 'book:page-create' book.id %}"
                               class="card-subtitle btn btn-primary btn-sm mb-2">
                                <i class="fa fa-plus fa-fw"></i> 추가
                            </a>
                        {% endif %}
                        <ul class="pl-0 mb-0 no-bullet">
                            {% book_toc book %}
                                <li class="mb-1 mb-md-2 no-bullet">
                                    <a href="{% url 'book:page-detail' book.id category.id %}">
                                        {{ category.title }}
                                    </a>
                                    {% if request.user.is_superuser %}
                                        {% if category.status == category.STATUS_CHOICES.draft or category.status == category.STATUS_CHOICES.private %}
                                            <small class="text-danger">
                                                [{{ category.get_status_display }}]
                                            </small>
                                        {% endif %}
                                    {% endif %}
                                </li>
                                {% if not category.is_leaf_node %}
                                    <ul class="pl-3 no-bullet">
                                        {{ children }}
                                    </ul>
                                {% endif %}
                            {% end_book_toc %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-8 book-page">
                {% block main_content %}{% endblock %}
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

book/templates/book/2_columns_book.html
{% extends "rakmai/base.html" %}

{% load i18n %}
{% load book_tags %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- Sidebar Widgets Column -->
            <div class="col-12 col-md-3">
                <div class="card my-2 my-md-4">
                    <h6 class="card-header py-2">
                        {% if user.is_superuser %}
                            <a href="{% url 'admin:book_book_change' book.id %}">
                                {{ book.title }}
                            </a>
                        {% else %}
                            <a href="{% url 'book:book-detail' book.slug %}">
                                {{ book.title }}
                            </a>
                        {% endif %}
                    </h6>
                    <div class="card-body pt-1 pb-0">
                        <h6 class="card-title text-center mb-1">
                            목차
                            <a href="#collapse0" data-toggle="collapse" class="ml-2" id="collapseLink0">
                                <i class="fa fa-plus fa-fw"></i>
                            </a>
                            {% if user.is_superuser %}
                                <a href="{% url 'book:page-create' book.slug %}"
                                   class="btn btn-outline-info btn-sm ml-5 mt-1 mb-2">
                                    <i class="fa fa-plus fa-fw"></i> 추가
                                </a>
                            {% endif %}
                        </h6>

                        <ul class="pl-0 mb-0 no-bullet" id="collapse0">
                            {% book_toc book %}
                                <li class="mb-1 mb-md-2 no-bullet">
                                    <a href="{% url 'book:page-detail' book.slug category.id %}">
                                        {{ category.title }}
                                    </a>
                                    {% if user.is_superuser %}
                                        {% if category.status == category.STATUS_CHOICES.draft or category.status == category.STATUS_CHOICES.private %}
                                            <small class="text-danger">
                                                [{{ category.get_status_display }}]
                                            </small>
                                        {% endif %}
                                    {% endif %}
                                </li>
                                {% if not category.is_leaf_node %}
                                    <ul class="pl-3 no-bullet">
                                        {{ children }}
                                    </ul>
                                {% endif %}
                            {% end_book_toc %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-9 book-page">
                {% block main_content %}{% endblock %}
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

book/templates/book/_breadcrumbs_article.html
{% load i18n %}
<div class="row">
    <div class="col">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mt-0 mt-md-4 mb-1 py-1">
                <li class="breadcrumb-item"><a href="{% url 'book:book-list' %}">{% trans "books" %}</a></li>
                {% for crumb in breadcrumbs %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'book:article-category-list' category_slug crumb.slug %}">{{ crumb.title }}</a>
                    </li>
                {% endfor %}
                <li class="breadcrumb-item active">{{ article.title }}</li>
            </ol>
        </nav>
    </div>
</div>

book/templates/book/_breadcrumbs_book.html
{% load i18n %}
<div class="row">
    <div class="col">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mt-0 mb-1 my-md-4 py-1">
                <li class="breadcrumb-item"><a href="{% url 'book:book-list' %}">{% trans "books" %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'book:book-detail' book.slug %}">{{ book.title }}</a></li>
                {% for crumb in breadcrumbs %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'book:page-detail' book.slug crumb.id %}">{{ crumb.title }}</a>
                    </li>
                {% endfor %}
                <li class="breadcrumb-item active">{{ page.title }}</li>
            </ol>
        </nav>
    </div>
</div>

book/templates/book/article_detail.html
{% extends "./2_columns_article.html" %}

{% load i18n %}
{% load static %}
{% load rakmai_filters %}
{% load book_tags %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static "js/replace-article-thai.js" %}"></script>
{% endblock %}

{% block main_content %}
    {% get_article_ancestor_path article.category.id as breadcrumbs %}
    {% include "./_breadcrumbs_article.html" with breadcrumbs=breadcrumbs %}

    <h5 class="mt-1 pb-1 border-bottom border-secondary">
        {% if user.is_superuser %}
            <span class="btn btn-outline-success btn-sm mb-1 mr-2">{{ article.category }}</span>
            <a href="{% url 'book:article-update' category_slug article.id %}">{{ article.title }}</a>
            <a href="{% url 'admin:book_article_change' article.id %}"
               class="btn btn-outline-info btn-sm mb-1 ml-2">
                <i class="fa fa-pencil fa-fw"></i> {% trans "Edit" %}
            </a>
            <a href="{% url 'admin:book_article_delete' article.id %}"
               class="btn btn-outline-danger btn-sm mb-1">
                <i class="fa fa-trash fa-fw"></i> {% trans "Delete Article" %}
            </a>
        {% else %}
            {{ article.title }}
        {% endif %}
    </h5>

    {% if article.youtube %}
        <div class="row my-1">
            <div class="col">
                <p class="youtube">
                    <iframe src="{{ article.youtube }}" frameborder="0" allowfullscreen></iframe>
                </p>
            </div>
        </div>
    {% endif %}

    <div class="row my-1">
        <div class="col paragraph thai-font" id="content1">
            {{ article.content|markdownify }}
        </div>
    </div>

    {% if words %}
        <h5 class="my-2 pb-2 border-bottom border-secondary">
            주요 어휘
            <a href="#collapse1" data-toggle="collapse" class="ml-2" id="collapseLink1">
                <i class="fa fa-plus fa-fw"></i>
            </a>
        </h5>
        <div class="collapse" id="collapse1">
            {% for word in words %}
                <div class="row my-1">
                    <div class="col-md-3 thai-font">
                        <a href="{% url 'voca:entry-detail' word.id %}">
                            {{ word.title }}
                        </a>
                    </div>
                    <div class="col-md-3 thai-font">
                        {{ word.pronunciation }}
                    </div>
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            {% for meaning in word.meanings.all %}
                                <li class="mb-2">{{ meaning.get_part_display }} - {{ meaning.meaning }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if article.content1 %}
        <h5 class="my-2 pb-2 border-bottom border-secondary">
            문법 및 표현
            <a href="#collapse2" data-toggle="collapse" class="ml-2" id="collapseLink2">
                <i class="fa fa-plus fa-fw"></i>
            </a>
        </h5>
        <div class="row my-1 my-md-3 collapse" id="collapse2">
            <div class="col paragraph" id="content2">
                {{ article.content1|markdownify }}
            </div>
        </div>
    {% endif %}

    {% if article.content2 %}
        <h5 class="my-2 pb-2 border-bottom border-secondary">
            본문 해석/의역
            <a href="#collapse3" data-toggle="collapse" class="ml-2" id="collapseLink3">
                <i class="fa fa-plus fa-fw"></i>
            </a>
        </h5>
        <div class="row my-1 my-md-3 collapse" id="collapse3">
            <div class="col paragraph" id="content3">
                {{ article.content2|markdownify }}
            </div>
        </div>
    {% endif %}
    <hr>
    <div class="row my-1 my-md-3">
        <div class="col text-right mr-2">
            {% trans "last modified" %}: {{ article.updated }}
        </div>
    </div>
    <a href="{% url 'book:article-list' category_slug %}?page={{ request.GET.page }}"
       class="btn btn-outline-secondary btn-block my-2">
        <i class="fa fa-list-ul fa-fw" aria-hidden="true"></i>&nbsp;{% trans "List" %}
    </a>
{% endblock %}

book/templates/book/book_detail.html
{% extends "./2_columns_book.html" %}

{% load i18n %}
{% load rakmai_filters %}
{% load book_tags %}

{% block main_content %}
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mt-0 mb-1 my-md-4 py-1">
                    <li class="breadcrumb-item"><a href="{% url 'book:book-list' %}">{% trans "books" %}</a></li>
                    <li class="breadcrumb-item active">{{ book.title }}</li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col paragraph">
            <div class="pl-2">
                {{ book.description|markdownify }}
            </div>
        </div>
    </div>
    <div class="row my-2">
        <div class="col">
            <ul>
                {% if user.is_superuser %}
                    <li class="my-1">{% trans "status" %}: {{ book.get_status_display }}</li>
                {% endif %}
                <li class="my-1">{% trans "license" %}: {{ book.get_license_display }}</li>
                <li class="my-1">{% trans "updated date" %}: {{ book.updated|date:'Y.m.d H:i' }}</li>
            </ul>
        </div>
    </div>
{% endblock %}