board/urls.py
from django.conf.urls import url

from .views import (
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView,
)

app_name = 'board'

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$',
        MessageListView.as_view(), name='message-list'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        MessageDetailView.as_view(), name='message-detail'),
    url(r'^(?P<slug>[-\w]+)/new/$',
        MessageCreateView.as_view(), name='message-new'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/edit/$',
        MessageUpdateView.as_view(), name='message-edit'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/delete/$',
        MessageDeleteView.as_view(), name='message-delete'),
]

book/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    PageSitemap, ArticleSitemap
)
from .views import (
    BookListView, BookDetailView,
    PageDetailView, PageCreateView, PageUpdateView,
    ArticleListView, ArticleDetailView, ArticleCategoryListView, ArticleCreateView, ArticleUpdateView,
)

app_name = 'book'

sitemaps_page = {
    'sitemap': PageSitemap(),
}

sitemaps_article = {
    'sitemap': ArticleSitemap(),
}

urlpatterns = [
    url(r'^$',
        BookListView.as_view(), name='book-list'),
    url(r'^(?P<slug>[-\w]+)/$',
        BookDetailView.as_view(), name='book-detail'),

    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/$',
        PageDetailView.as_view(), name='page-detail'),
    url(r'^(?P<book>[-\w]+)/create$',
        PageCreateView.as_view(), name='page-create'),
    url(r'^(?P<book>[-\w]+)/(?P<pk>\d+)/update/',
        PageUpdateView.as_view(), name='page-update'),

    url(r'^article/(?P<category>[-\w]+)/$',
        ArticleListView.as_view(), name='article-list'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/$',
        ArticleDetailView.as_view(), name='article-detail'),
    url(r'^article/(?P<category>[-\w]+)/create$',
        ArticleCreateView.as_view(), name='article-create'),
    url(r'^article/(?P<category>[-\w]+)/(?P<pk>\d+)/update/',
        ArticleUpdateView.as_view(), name='article-update'),
    url(r'^article/(?P<category>[-\w]+)/category/(?P<slug>[-\w]+)$',
        ArticleCategoryListView.as_view(), name='article-category-list'),

    url(r'^sitemap-page\.xml$',
        sitemap, {'sitemaps': sitemaps_page}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-article\.xml$',
        sitemap, {'sitemaps': sitemaps_article}, name='django.contrib.sitemaps.views.sitemap'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin

from rakmai.views import HomeView

urlpatterns = [
    url(r'^$',
        HomeView.as_view(), name='home'),
    url(r'{}'.format(settings.ADMIN_URL),
        admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^voca/', include('voca.urls', namespace='voca')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^help/', include('help.urls', namespace='help')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.GOOGLE_OTP_ENABLED:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite

help/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import (
    NoticeSitemap, PostSitemap
)
from .views import (
    PostDetailView, NoticeDetailView, NoticeListView,
    ContactCreateView, ContactDoneView,
)

app_name = 'help'

sitemaps_notice = {
    'sitemap': NoticeSitemap(),
}

sitemaps_post = {
    'sitemap': PostSitemap(),
}

urlpatterns = [
    url(r'^page/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),

    url(r'^notice/$',
        NoticeListView.as_view(), name='notice-list'),
    url(r'^notice/(?P<pk>\d+)/$',
        NoticeDetailView.as_view(), name='notice-detail'),

    url(r'^contact/create$',
        ContactCreateView.as_view(), name='contact-create'),
    url(r'^contact/done$',
        ContactDoneView.as_view(), name='contact-done'),

    url(r'^sitemap-notice\.xml$',
        sitemap, {'sitemaps': sitemaps_notice}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^sitemap-post\.xml$',
        sitemap, {'sitemaps': sitemaps_post}, name='django.contrib.sitemaps.views.sitemap'),
]

voca/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from .sitemaps import EntrySitemap
from .views import (
    EntryListView, EntryDetailView,
    LevelListView, EntryLevelListView, EntryLevelDetailView,
    CategoryTemplateView, EntryCategoryView, EntryCategoryDetailView,
    TextbookListView, TextbookEntryListView,
)

app_name = 'voca'

sitemaps_entry = {
    'sitemap': EntrySitemap(),
}

urlpatterns = [
    url(r'^entry/$',
        EntryListView.as_view(), name='entry-list'),
    url(r'^entry/(?P<pk>\d+)/$',
        EntryDetailView.as_view(), name='entry-detail'),

    url(r'^level/$',
        LevelListView.as_view(), name='level-list'),
    url(r'^level/(?P<level>[\w]+)$',
        EntryLevelListView.as_view(), name='level-entry-list'),
    url(r'^level/(?P<level>[\w]+)/(?P<pk>\d+)/$',
        EntryLevelDetailView.as_view(), name='level-entry-detail'),

    url(r'^category/$',
        CategoryTemplateView.as_view(), name='category-list'),
    url(r'^category/(?P<slug>[-\w]+)/$',
        EntryCategoryView.as_view(), name='entry-category'),
    url(r'^category/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        EntryCategoryDetailView.as_view(), name='category-entry-detail'),

    url(r'^textbook/$',
        TextbookListView.as_view(), name='textbook-list'),
    url(r'^textbook/(?P<slug>[-\w]+)/$',
        TextbookEntryListView.as_view(), name='textbook-entry-list'),

    url(r'^sitemap-entry\.xml$',
        sitemap, {'sitemaps': sitemaps_entry}, name='django.contrib.sitemaps.views.sitemap'),
]

rakmai/models.py
import uuid

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class MenuItem(MPTTModel):
    MATCH_CHOICES = Choices(
        (0, 'equals', _('equals')),
        (1, 'startswith', _('startswith')),
    )

    TARGET_CHOICES = Choices(
        (0, 'self', _('_self')),
        (1, 'blank', _('blank')),
    )

    parent = TreeForeignKey(
        'self',
        verbose_name=_('parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True,
        on_delete=models.SET_NULL,
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=255,
        help_text=_('Site menu item title. Can contain template variables E.g.: {{ mytitle }}'),
    )

    url = models.CharField(
        verbose_name=_('url'),
        max_length=255,
        db_index=True,
        help_text=_('Exact URL or URL pattern'),
    )

    match = models.IntegerField(
        verbose_name=_('match'),
        choices=MATCH_CHOICES,
        default=MATCH_CHOICES.equals,
    )

    target = models.IntegerField(
        verbose_name=_('target'),
        choices=TARGET_CHOICES,
        default=TARGET_CHOICES.self,
    )

    class Meta:
        verbose_name = _('menu item')
        verbose_name_plural = _('menu items')
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title


class AbstractPage(TimeStampedModel):
    title = models.CharField(
        verbose_name=_('title'),
        max_length=255,
        help_text=_("The page title as you'd like it to be seen by the public"),
    )

    description = models.CharField(
        verbose_name=_('description'),
        max_length=255,
        help_text=_("A short description not longer than 155 characters. Don't use double quotes."),
        blank=True,
    )

    keywords = models.CharField(
        verbose_name=_('keywords'),
        max_length=255,
        help_text=_("A comma-separated list of keywords. Don't use double quotes."),
        blank=True,
    )

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('owner'),
        null=True,
        blank=True,
        editable=True,
        on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_owned",
    )

    class Meta:
        abstract = True


class AbstractCategory(TimeStampedModel, MPTTModel):
    parent = TreeForeignKey(
        'self',
        verbose_name=_('parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True,
        on_delete=models.SET_NULL,
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=128,
    )

    slug = models.SlugField(
        verbose_name=_('slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        unique=True,
        allow_unicode=True,
    )

    class Meta:
        abstract = True
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['created']


class AbstractAttachment(models.Model):
    name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name=_('file name'),
    )

    # PK is a private identifier
    uid = models.UUIDField(
        verbose_name=_('public identifier'),
        unique=True,
        default=uuid.uuid4,
        editable=False,
    )

    file = models.FileField(
        verbose_name=_('uploaded file'),
        upload_to="attachments",
    )

    created = models.DateTimeField(
        verbose_name=_('created time'),
        auto_now_add=True,
    )

    class Meta:
        abstract = True
        verbose_name = _('attachment')
        verbose_name_plural = _('attachments')
        ordering = ['-created']

    def __str__(self):
        return self.name

rakmai/views.py
import logging

from django.utils.translation import ugettext_lazy as _
from django.views import generic


class HomeView(generic.TemplateView):
    logger = logging.getLogger(__name__)

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['page_title'] = _('Thai for All')
        return context

    def get_template_names(self):
        return 'rakmai/home.html'

rakmai/templates/rakmai/home.html
{% extends "./base.html" %}

{% load i18n %}
{% load help_tags %}
{% load board_tags %}
{% load book_tags %}

{% block content %}
    <div class="container">
        <header class="jumbotron my-2 my-md-3 py-1 py-md-4">
            <h3 class="display-5 text-light mb-3">위드타이</h3>
            <p class="jumbotron-text p-3 lead text-light">
                모두의 태국어<br/>
                누구나 쉽고 빠르게 재밌게 태국어를 배웁니다.<br/>
                쉬운 내용부터 중고급 내용까지 다룹니다.<br/>
            </p>
        </header>

        <!-- 게시물 목록 -->
        <div class="row">
            <div class="col-lg-4 mb-2">
                <div class="card h-100">
                    <h5 class="card-header py-md-2">
                        <a href="{% url 'board:message-list' 'free' %}">자유게시판</a>
                    </h5>
                    <div class="card-body py-1">
                        <ul class="list-unstyled mb-0">
                            {% get_messages 'free' 5 as free_messages %}
                            {% for message in free_messages %}
                                <li class="my-1">
                                    <a href="{% url 'help:notice-detail' message.id %}">
                                        {{ message.title }}
                                    </a>
                                </li>
                            {% empty %}
                                <li class="my-1">
                                    {% trans "No message" %}
                                </li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-2">
                <div class="card h-100">
                    <h5 class="card-header py-md-2">
                        <a href="{% url 'board:message-list' 'qna' %}">묻고답하기</a>
                    </h5>
                    <div class="card-body py-1">
                        <ul class="list-unstyled mb-0">
                            {% get_messages 'qna' 5 as qna_messages %}
                            {% for message in qna_messages %}
                                <li class="my-1">
                                    <a href="{% url 'help:notice-detail' message.id %}">
                                        {{ message.title }}
                                    </a>
                                </li>
                            {% empty %}
                                <li class="my-1">
                                    {% trans "No message" %}
                                </li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-2">
                <div class="card h-100">
                    <h5 class="card-header py-md-2">
                        <a href="{% url 'help:notice-list' %}">
                            공지사항
                        </a>
                    </h5>
                    <div class="card-body py-1">
                        <ul class="list-unstyled mb-0">
                            {% get_notice as notice_messages %}
                            {% for message in notice_messages %}
                                <li class="my-1">
                                    <a href="{% url 'help:notice-detail' message.id %}">
                                        {{ message.title }}
                                    </a>
                                </li>
                            {% empty %}
                                <li class="my-1">
                                    {% trans "No message" %}
                                </li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                                <li class="my-1">&nbsp;</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <h5 class="mt-md-2 mb-md-3 pl-md-3">
            <a href="{% url 'book:book-list' %}">
                {% trans "books" %}
            </a>
        </h5>
        <div class="row">
            {% get_books 4 as books %}
            {% for book in books %}
                <div class="col-12 col-sm-12 col-md-4 col-lg-3 mb-4">
                    <div class="card h-100">
                        <div class="card-body py-1 py-md-2">
                            <h5 class="card-title text-center mb-1 mb-md-3">
                                <a href="{% url 'book:book-detail' book.slug %}">
                                    {{ book.title }}
                                </a>
                            </h5>
                            <p class="card-text paragraph">
                                {{ book.description|truncatechars:35 }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- /.container -->
{% endblock %}